use super::{
    ARTIFACT_DIRECTORY, ArtifactError, Command, OpenOptions, Path, PathBuf, Stdio, Write, fs,
};

pub(super) fn git_head(repository: &Path) -> String {
    Command::new("git")
        .arg("-C")
        .arg(repository)
        .args(["rev-parse", "HEAD"])
        .stderr(Stdio::null())
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|output| output.trim().to_owned())
        .unwrap_or_default()
}

pub(super) fn configure_merge_driver(repository: &Path) {
    let _ = Command::new("git")
        .arg("-C")
        .arg(repository)
        .args(["config", "merge.ours.driver", "true"])
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
}

pub(super) fn ensure_gitattributes(repository: &Path) -> Result<(), ArtifactError> {
    let path = repository.join(ARTIFACT_DIRECTORY).join(".gitattributes");
    match OpenOptions::new().write(true).create_new(true).open(&path) {
        Ok(mut file) => {
            file.write_all(
                b"# Auto-generated by Goldeneye\n# Prevent merge conflicts on compressed artifact\ngraph.db.zst binary merge=ours\n",
            )
            .map_err(|source| io_error("writing", &path, source))?;
            file.sync_all()
                .map_err(|source| io_error("syncing", &path, source))?;
            Ok(())
        }
        Err(source) if source.kind() == std::io::ErrorKind::AlreadyExists => Ok(()),
        Err(source) => Err(io_error("creating", &path, source)),
    }
}

pub(super) fn remove_sidecars(path: &Path) {
    for suffix in ["-wal", "-shm"] {
        let sidecar = PathBuf::from(format!("{}{suffix}", path.display()));
        let _ = fs::remove_file(sidecar);
    }
}

pub(super) fn io_error(
    operation: &'static str,
    path: &Path,
    source: std::io::Error,
) -> ArtifactError {
    ArtifactError::Io {
        operation,
        path: path.to_path_buf(),
        source,
    }
}
