// goldeneye-full-pack-lock-sha256: ce668d1c07d4f7dd72fd8f167f94d218bfc933a1ccd9ffa52277354968c950c1
// Generated by cargo xtask grammars generate-provider; do not edit.

use tree_sitter_language::LanguageFn;

pub(crate) const FULL_PACK_LOCK_SHA256: &str = "ce668d1c07d4f7dd72fd8f167f94d218bfc933a1ccd9ffa52277354968c950c1";
pub(crate) const FULL_PACK_UPSTREAM_COMMIT: &str = "2469ecc3a7a2f80debe296e1f17a1efcfdb9450c";
pub(crate) const DECLARED_LANGUAGE_COUNT: usize = 160;
pub(crate) const AVAILABLE_LANGUAGE_COUNT: usize = 159;
pub(crate) const UNIQUE_GRAMMAR_COUNT: usize = 157;
pub(crate) const COMPILED_SOURCE_COUNT: usize = 159;
pub(crate) const ORPHAN_SOURCE_COUNT: usize = 2;

#[derive(Clone, Copy)]
pub(crate) struct GeneratedGrammar {
    pub(crate) name: &'static str,
    pub(crate) exported_symbol: &'static str,
    pub(crate) abi: u32,
    pub(crate) scanner_language: &'static str,
    pub(crate) source_hash: &'static str,
}

#[derive(Clone, Copy)]
pub(crate) enum GeneratedAvailability {
    Available { grammar_index: usize },
    Unavailable { reason: &'static str },
}

#[derive(Clone, Copy)]
pub(crate) struct GeneratedLanguage {
    pub(crate) id: &'static str,
    pub(crate) availability: GeneratedAvailability,
}

unsafe extern "C" {
    #[link_name = "goldeneye_full_tree_sitter_ada"]
    fn grammar_000() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_agda"]
    fn grammar_001() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_apex"]
    fn grammar_002() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_asm"]
    fn grammar_003() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_astro"]
    fn grammar_004() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_awk"]
    fn grammar_005() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_bash"]
    fn grammar_006() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_beancount"]
    fn grammar_007() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_bibtex"]
    fn grammar_008() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_bicep"]
    fn grammar_009() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_bitbake"]
    fn grammar_010() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_blade"]
    fn grammar_011() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_c"]
    fn grammar_012() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_c_sharp"]
    fn grammar_013() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_cairo"]
    fn grammar_014() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_capnp"]
    fn grammar_015() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_cfml"]
    fn grammar_016() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_cfscript"]
    fn grammar_017() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_clojure"]
    fn grammar_018() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_cmake"]
    fn grammar_019() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_COBOL"]
    fn grammar_020() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_commonlisp"]
    fn grammar_021() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_cpp"]
    fn grammar_022() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_crystal"]
    fn grammar_023() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_css"]
    fn grammar_024() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_csv"]
    fn grammar_025() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_cuda"]
    fn grammar_026() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_d"]
    fn grammar_027() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_dart"]
    fn grammar_028() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_devicetree"]
    fn grammar_029() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_diff"]
    fn grammar_030() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_dockerfile"]
    fn grammar_031() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_dotenv"]
    fn grammar_032() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_elisp"]
    fn grammar_033() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_elixir"]
    fn grammar_034() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_elm"]
    fn grammar_035() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_erlang"]
    fn grammar_036() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_fennel"]
    fn grammar_037() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_fish"]
    fn grammar_038() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_form"]
    fn grammar_039() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_fortran"]
    fn grammar_040() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_fsharp"]
    fn grammar_041() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_func"]
    fn grammar_042() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gdscript"]
    fn grammar_043() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gitattributes"]
    fn grammar_044() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gitignore"]
    fn grammar_045() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gleam"]
    fn grammar_046() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_glsl"]
    fn grammar_047() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gn"]
    fn grammar_048() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_go"]
    fn grammar_049() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gomod"]
    fn grammar_050() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_gotmpl"]
    fn grammar_051() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_graphql"]
    fn grammar_052() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_groovy"]
    fn grammar_053() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_hare"]
    fn grammar_054() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_haskell"]
    fn grammar_055() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_hcl"]
    fn grammar_056() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_hlsl"]
    fn grammar_057() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_html"]
    fn grammar_058() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_hyprlang"]
    fn grammar_059() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_ini"]
    fn grammar_060() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_ispc"]
    fn grammar_061() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_janet_simple"]
    fn grammar_062() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_java"]
    fn grammar_063() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_javascript"]
    fn grammar_064() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_jinja2"]
    fn grammar_065() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_jsdoc"]
    fn grammar_066() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_json"]
    fn grammar_067() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_json5"]
    fn grammar_068() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_jsonnet"]
    fn grammar_069() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_julia"]
    fn grammar_070() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_just"]
    fn grammar_071() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_kconfig"]
    fn grammar_072() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_kdl"]
    fn grammar_073() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_kotlin"]
    fn grammar_074() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_lean"]
    fn grammar_075() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_linkerscript"]
    fn grammar_076() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_liquid"]
    fn grammar_077() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_llvm"]
    fn grammar_078() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_lua"]
    fn grammar_079() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_luau"]
    fn grammar_080() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_magma"]
    fn grammar_081() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_make"]
    fn grammar_082() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_markdown"]
    fn grammar_083() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_matlab"]
    fn grammar_084() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_mermaid"]
    fn grammar_085() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_meson"]
    fn grammar_086() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_mojo"]
    fn grammar_087() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_move"]
    fn grammar_088() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_nasm"]
    fn grammar_089() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_nickel"]
    fn grammar_090() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_nix"]
    fn grammar_091() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_objc"]
    fn grammar_092() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_ocaml"]
    fn grammar_093() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_odin"]
    fn grammar_094() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_pascal"]
    fn grammar_095() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_perl"]
    fn grammar_096() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_php_only"]
    fn grammar_097() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_pine"]
    fn grammar_098() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_pkl"]
    fn grammar_099() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_po"]
    fn grammar_100() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_pony"]
    fn grammar_101() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_powershell"]
    fn grammar_102() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_prisma"]
    fn grammar_103() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_properties"]
    fn grammar_104() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_proto"]
    fn grammar_105() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_puppet"]
    fn grammar_106() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_purescript"]
    fn grammar_107() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_python"]
    fn grammar_108() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_qmljs"]
    fn grammar_109() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_r"]
    fn grammar_110() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_racket"]
    fn grammar_111() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_regex"]
    fn grammar_112() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_requirements"]
    fn grammar_113() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_rescript"]
    fn grammar_114() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_ron"]
    fn grammar_115() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_rst"]
    fn grammar_116() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_ruby"]
    fn grammar_117() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_rust"]
    fn grammar_118() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_scala"]
    fn grammar_119() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_scheme"]
    fn grammar_120() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_scss"]
    fn grammar_121() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_slang"]
    fn grammar_122() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_smali"]
    fn grammar_123() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_smithy"]
    fn grammar_124() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_solidity"]
    fn grammar_125() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_soql"]
    fn grammar_126() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_sosl"]
    fn grammar_127() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_sql"]
    fn grammar_128() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_squirrel"]
    fn grammar_129() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_ssh_config"]
    fn grammar_130() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_starlark"]
    fn grammar_131() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_svelte"]
    fn grammar_132() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_sway"]
    fn grammar_133() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_swift"]
    fn grammar_134() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_systemverilog"]
    fn grammar_135() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_tablegen"]
    fn grammar_136() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_tcl"]
    fn grammar_137() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_teal"]
    fn grammar_138() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_templ"]
    fn grammar_139() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_thrift"]
    fn grammar_140() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_tlaplus"]
    fn grammar_141() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_toml"]
    fn grammar_142() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_tsx"]
    fn grammar_143() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_typescript"]
    fn grammar_144() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_typst"]
    fn grammar_145() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_verilog"]
    fn grammar_146() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_vhdl"]
    fn grammar_147() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_vim"]
    fn grammar_148() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_vue"]
    fn grammar_149() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_wgsl"]
    fn grammar_150() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_wit"]
    fn grammar_151() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_wolfram"]
    fn grammar_152() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_xml"]
    fn grammar_153() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_yaml"]
    fn grammar_154() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_zig"]
    fn grammar_155() -> *const ();
    #[link_name = "goldeneye_full_tree_sitter_zsh"]
    fn grammar_156() -> *const ();
}

const FACTORIES: [unsafe extern "C" fn() -> *const (); 157] = [
    grammar_000,
    grammar_001,
    grammar_002,
    grammar_003,
    grammar_004,
    grammar_005,
    grammar_006,
    grammar_007,
    grammar_008,
    grammar_009,
    grammar_010,
    grammar_011,
    grammar_012,
    grammar_013,
    grammar_014,
    grammar_015,
    grammar_016,
    grammar_017,
    grammar_018,
    grammar_019,
    grammar_020,
    grammar_021,
    grammar_022,
    grammar_023,
    grammar_024,
    grammar_025,
    grammar_026,
    grammar_027,
    grammar_028,
    grammar_029,
    grammar_030,
    grammar_031,
    grammar_032,
    grammar_033,
    grammar_034,
    grammar_035,
    grammar_036,
    grammar_037,
    grammar_038,
    grammar_039,
    grammar_040,
    grammar_041,
    grammar_042,
    grammar_043,
    grammar_044,
    grammar_045,
    grammar_046,
    grammar_047,
    grammar_048,
    grammar_049,
    grammar_050,
    grammar_051,
    grammar_052,
    grammar_053,
    grammar_054,
    grammar_055,
    grammar_056,
    grammar_057,
    grammar_058,
    grammar_059,
    grammar_060,
    grammar_061,
    grammar_062,
    grammar_063,
    grammar_064,
    grammar_065,
    grammar_066,
    grammar_067,
    grammar_068,
    grammar_069,
    grammar_070,
    grammar_071,
    grammar_072,
    grammar_073,
    grammar_074,
    grammar_075,
    grammar_076,
    grammar_077,
    grammar_078,
    grammar_079,
    grammar_080,
    grammar_081,
    grammar_082,
    grammar_083,
    grammar_084,
    grammar_085,
    grammar_086,
    grammar_087,
    grammar_088,
    grammar_089,
    grammar_090,
    grammar_091,
    grammar_092,
    grammar_093,
    grammar_094,
    grammar_095,
    grammar_096,
    grammar_097,
    grammar_098,
    grammar_099,
    grammar_100,
    grammar_101,
    grammar_102,
    grammar_103,
    grammar_104,
    grammar_105,
    grammar_106,
    grammar_107,
    grammar_108,
    grammar_109,
    grammar_110,
    grammar_111,
    grammar_112,
    grammar_113,
    grammar_114,
    grammar_115,
    grammar_116,
    grammar_117,
    grammar_118,
    grammar_119,
    grammar_120,
    grammar_121,
    grammar_122,
    grammar_123,
    grammar_124,
    grammar_125,
    grammar_126,
    grammar_127,
    grammar_128,
    grammar_129,
    grammar_130,
    grammar_131,
    grammar_132,
    grammar_133,
    grammar_134,
    grammar_135,
    grammar_136,
    grammar_137,
    grammar_138,
    grammar_139,
    grammar_140,
    grammar_141,
    grammar_142,
    grammar_143,
    grammar_144,
    grammar_145,
    grammar_146,
    grammar_147,
    grammar_148,
    grammar_149,
    grammar_150,
    grammar_151,
    grammar_152,
    grammar_153,
    grammar_154,
    grammar_155,
    grammar_156,
];

pub(crate) static GRAMMARS: [GeneratedGrammar; 157] = [
    GeneratedGrammar { name: "ada", exported_symbol: "tree_sitter_ada", abi: 14, scanner_language: "none", source_hash: "fe745430ec54b5c325ce94f94473855fdedde38d9f98e4cd01d5431ef438ff0e" },
    GeneratedGrammar { name: "agda", exported_symbol: "tree_sitter_agda", abi: 14, scanner_language: "c", source_hash: "42c8fc238751b43e9dc7c7c85e2692ebecc93062d3d507949d701e7ccb8cd101" },
    GeneratedGrammar { name: "apex", exported_symbol: "tree_sitter_apex", abi: 14, scanner_language: "none", source_hash: "5f0db6c9e6b02343a503023833dd22ef05acee94d199f3150d04ae3b87f5d3dc" },
    GeneratedGrammar { name: "assembly", exported_symbol: "tree_sitter_asm", abi: 14, scanner_language: "none", source_hash: "913e197949023e9616d64bcfb7f60b7867a99d7449213da5e95813e1ae057b33" },
    GeneratedGrammar { name: "astro", exported_symbol: "tree_sitter_astro", abi: 14, scanner_language: "c", source_hash: "a7781cbf763b9a4ef3ca4e8d67b0ca73542d051d2e0b1fa4ed27f4943b48bccd" },
    GeneratedGrammar { name: "awk", exported_symbol: "tree_sitter_awk", abi: 14, scanner_language: "c", source_hash: "c8ee53f1c19095a453d440a2b5f62667aee29975787228745c76c66d4b13681e" },
    GeneratedGrammar { name: "bash", exported_symbol: "tree_sitter_bash", abi: 15, scanner_language: "c", source_hash: "a0abce117b0364cff1a3c8fd1028cda42dcdc65440844e97adb1d77032fc9b94" },
    GeneratedGrammar { name: "beancount", exported_symbol: "tree_sitter_beancount", abi: 15, scanner_language: "c", source_hash: "8af9e3ecaeffed392e86ffbc5b5158edd965ee7c6d814f5244b4eda06e771c09" },
    GeneratedGrammar { name: "bibtex", exported_symbol: "tree_sitter_bibtex", abi: 15, scanner_language: "none", source_hash: "a7362788f3e00163ce1848702d710897105b7eb53181b4979c1b98df36ddb15e" },
    GeneratedGrammar { name: "bicep", exported_symbol: "tree_sitter_bicep", abi: 14, scanner_language: "c", source_hash: "92d216511fb838aff54dc4e7f796f7ca369748180e268d4bb52f86ceeba31e4f" },
    GeneratedGrammar { name: "bitbake", exported_symbol: "tree_sitter_bitbake", abi: 14, scanner_language: "c", source_hash: "ae8dd493e6c53d114be396d37fbda236caed42493c8ba65411a6b9a9ae1f912e" },
    GeneratedGrammar { name: "blade", exported_symbol: "tree_sitter_blade", abi: 15, scanner_language: "c", source_hash: "8914748479bdfa3a5c45e8aabb9fa777becef2f511d36d03df31af3f82999cd4" },
    GeneratedGrammar { name: "c", exported_symbol: "tree_sitter_c", abi: 15, scanner_language: "none", source_hash: "8d965f5b04cbfa3661b3ba3c8af8c7ed15a0cceadb562a9d97f7e152c5db52c6" },
    GeneratedGrammar { name: "c_sharp", exported_symbol: "tree_sitter_c_sharp", abi: 15, scanner_language: "c", source_hash: "5a2b309113938f7fa8bfe72d3941b46d72a807329caf77fd20c7eeb54bc967f8" },
    GeneratedGrammar { name: "cairo", exported_symbol: "tree_sitter_cairo", abi: 14, scanner_language: "c", source_hash: "739851aa70d2741a0c054c21cde020660f1c9f2a0cd5e21514abd604558110b2" },
    GeneratedGrammar { name: "capnp", exported_symbol: "tree_sitter_capnp", abi: 14, scanner_language: "none", source_hash: "6d7c459c4147ac72ba9413ec10c4e0c69b3d0a4fc6a03b082bda416dd0d1b8f4" },
    GeneratedGrammar { name: "cfml", exported_symbol: "tree_sitter_cfml", abi: 15, scanner_language: "c", source_hash: "3a5b0a0232dea3eae6ce7608efbd0a02963d7ccf96d851d7375561a12a93efbd" },
    GeneratedGrammar { name: "cfscript", exported_symbol: "tree_sitter_cfscript", abi: 15, scanner_language: "c", source_hash: "76ef39225d02006c15852e9b375a06272fd0301feb6304cb41b953c7ff97ba04" },
    GeneratedGrammar { name: "clojure", exported_symbol: "tree_sitter_clojure", abi: 14, scanner_language: "none", source_hash: "f968fd0e0f25c44aaa7635afd9c4800dc32ff2e568a6a4cc15dc2585b1f241c7" },
    GeneratedGrammar { name: "cmake", exported_symbol: "tree_sitter_cmake", abi: 14, scanner_language: "c", source_hash: "1b550911c133fdb635ce1a43649110799b0fde7e94b250fe04b59c8372e9e86f" },
    GeneratedGrammar { name: "cobol", exported_symbol: "tree_sitter_COBOL", abi: 14, scanner_language: "c", source_hash: "d516c49844cae6c4a18cc793b27b48004fed858e1887aa119c5cf15e40a1bacf" },
    GeneratedGrammar { name: "commonlisp", exported_symbol: "tree_sitter_commonlisp", abi: 14, scanner_language: "none", source_hash: "0f8c079ac5d518a1d93ef02e139f152f62c3008aae5a7fc1cabcad095a62f019" },
    GeneratedGrammar { name: "cpp", exported_symbol: "tree_sitter_cpp", abi: 15, scanner_language: "c", source_hash: "3fbeb4c9b0ffa952fb4f2609d1b3c3261991660ec2ae7d37c1963a8d7b13d244" },
    GeneratedGrammar { name: "crystal", exported_symbol: "tree_sitter_crystal", abi: 15, scanner_language: "c", source_hash: "6d03826729cec00af5250b658f1aebac3a712e3bd731bfbac8b67695e9cb5411" },
    GeneratedGrammar { name: "css", exported_symbol: "tree_sitter_css", abi: 15, scanner_language: "c", source_hash: "a9b4694249ad00b843111bdea34a25f86d6ac34e99fa5f7facf285a2c69c9e87" },
    GeneratedGrammar { name: "csv", exported_symbol: "tree_sitter_csv", abi: 15, scanner_language: "none", source_hash: "f44af2de4f6033fa6c759bea96b025597284af23c91377677d20e9d63ce702e3" },
    GeneratedGrammar { name: "cuda", exported_symbol: "tree_sitter_cuda", abi: 15, scanner_language: "c", source_hash: "7aad74f37310dd68548efd0e25f3e2a297847f0d33cb345e953c0ea1514d1079" },
    GeneratedGrammar { name: "d", exported_symbol: "tree_sitter_d", abi: 14, scanner_language: "c", source_hash: "67d99f5636b72634f4d03394502f321dbf05adce5627637ded175ee6d1f3cfe9" },
    GeneratedGrammar { name: "dart", exported_symbol: "tree_sitter_dart", abi: 15, scanner_language: "c", source_hash: "6b4d186ad2c45747a382a501561990f199276540895710fb02533e51fd1d1960" },
    GeneratedGrammar { name: "devicetree", exported_symbol: "tree_sitter_devicetree", abi: 15, scanner_language: "none", source_hash: "49ce1d2738ddf1f5d17b6097e2243aa3721045991ae0007f043b8e73c403db54" },
    GeneratedGrammar { name: "diff", exported_symbol: "tree_sitter_diff", abi: 15, scanner_language: "none", source_hash: "6503521e6daeb832a0a9f3ad7b0d0cec2a3f3c4c271e1dc5d8379b44c24473f4" },
    GeneratedGrammar { name: "dockerfile", exported_symbol: "tree_sitter_dockerfile", abi: 14, scanner_language: "c", source_hash: "1f7682184acbc7b733ec3557a51dfe7c467a5340a6ec76a60f836a6dad573d22" },
    GeneratedGrammar { name: "dotenv", exported_symbol: "tree_sitter_dotenv", abi: 15, scanner_language: "c", source_hash: "65bd5dbdc36610d2d683f2a29f0662962c259779298f270c9caa61df32f8d49f" },
    GeneratedGrammar { name: "elisp", exported_symbol: "tree_sitter_elisp", abi: 15, scanner_language: "none", source_hash: "4cb8a0f4e153563ab912c45a5cacca3044b09ddb8f468b47a09e7a1c4e9be852" },
    GeneratedGrammar { name: "elixir", exported_symbol: "tree_sitter_elixir", abi: 14, scanner_language: "c", source_hash: "a26a0e1b628e282602699d2e5cd7ee47d36bacfc9ec5508ea11487aa3d43a8da" },
    GeneratedGrammar { name: "elm", exported_symbol: "tree_sitter_elm", abi: 15, scanner_language: "c", source_hash: "3c57fffbec31825480ea8b68c451375c0dc1cff56397725cfbcd7f90979f63c7" },
    GeneratedGrammar { name: "erlang", exported_symbol: "tree_sitter_erlang", abi: 14, scanner_language: "c", source_hash: "1c44dd1f76326d77a4883322e3a8374d70815bf13efe3cc44534888f1f400b97" },
    GeneratedGrammar { name: "fennel", exported_symbol: "tree_sitter_fennel", abi: 14, scanner_language: "none", source_hash: "7c4d38fab37ecd76868455fd755881aa3edec67925c5899be89240d92041ca64" },
    GeneratedGrammar { name: "fish", exported_symbol: "tree_sitter_fish", abi: 14, scanner_language: "c", source_hash: "6e52e05dcc0eb1dbdf3884576a215ceec316228ccafd71029e865d5efc432529" },
    GeneratedGrammar { name: "form", exported_symbol: "tree_sitter_form", abi: 15, scanner_language: "none", source_hash: "c69ec83aecaa84ea34121e8cd19ca57a912129c85f47b7ab5b48fe5ccf15d3a5" },
    GeneratedGrammar { name: "fortran", exported_symbol: "tree_sitter_fortran", abi: 15, scanner_language: "c", source_hash: "b82a0924c84ec8c04907dcc370ad2f3b3e699dd6b21503e1c401025129662dd7" },
    GeneratedGrammar { name: "fsharp", exported_symbol: "tree_sitter_fsharp", abi: 15, scanner_language: "c", source_hash: "cfad9452cd02c2f5c03f4d37aa0fdc5ea767ad2b7952dec9edf8796f61c584a5" },
    GeneratedGrammar { name: "func", exported_symbol: "tree_sitter_func", abi: 14, scanner_language: "none", source_hash: "73b8c680ff687f13fdcddf5a4b17f7a8824dd1b77fa66308cf141cca2a3fb727" },
    GeneratedGrammar { name: "gdscript", exported_symbol: "tree_sitter_gdscript", abi: 15, scanner_language: "c", source_hash: "357063bf2f3577a9cd5d91243994ba80958c51922b04ca62908c40828163654b" },
    GeneratedGrammar { name: "gitattributes", exported_symbol: "tree_sitter_gitattributes", abi: 14, scanner_language: "none", source_hash: "2444737ffa75429c1163ceb751aa1c3a839f8b74ff33f40424f1ed67b1de7f79" },
    GeneratedGrammar { name: "gitignore", exported_symbol: "tree_sitter_gitignore", abi: 13, scanner_language: "none", source_hash: "ddb50d6eaa603af9ed5106f000042f5e052e840f4d8f3506c89acd3466225aab" },
    GeneratedGrammar { name: "gleam", exported_symbol: "tree_sitter_gleam", abi: 15, scanner_language: "c", source_hash: "aafbf3282729b35cc2971d2b8d46c3061d11ede05524a80de683210f4b27772c" },
    GeneratedGrammar { name: "glsl", exported_symbol: "tree_sitter_glsl", abi: 14, scanner_language: "none", source_hash: "c21f6a361e1e5a26703abfe6dc114b7756c2cb74eee6ca57ddc4b33b76aeee54" },
    GeneratedGrammar { name: "gn", exported_symbol: "tree_sitter_gn", abi: 14, scanner_language: "c", source_hash: "eae9e6fefaecf51b7ae024e0d4f41b145176b9afca8f99a46a8a9e87482f68c4" },
    GeneratedGrammar { name: "go", exported_symbol: "tree_sitter_go", abi: 15, scanner_language: "none", source_hash: "b59cdf2b783326abd7c9d3e534c6b2b919b40ee0a92c55087529271bbd524e95" },
    GeneratedGrammar { name: "gomod", exported_symbol: "tree_sitter_gomod", abi: 15, scanner_language: "none", source_hash: "5f8e6afa59b08a9822f10a00bbbf82f13336d2dfe2bb68437b25abad9212dcb5" },
    GeneratedGrammar { name: "gotemplate", exported_symbol: "tree_sitter_gotmpl", abi: 15, scanner_language: "none", source_hash: "2294ebb2da2c12d30fa106c749fe8201fc880eab293f5607b62f33f5211488dc" },
    GeneratedGrammar { name: "graphql", exported_symbol: "tree_sitter_graphql", abi: 13, scanner_language: "none", source_hash: "26b490b4ec29159503a4bf8c663155634fbf5578101c511bd447e41bb8582269" },
    GeneratedGrammar { name: "groovy", exported_symbol: "tree_sitter_groovy", abi: 15, scanner_language: "none", source_hash: "d0fa71675e3eb0966a38a5d5eb9a7cdb1f543b4a862f21d9c61b3053b638e195" },
    GeneratedGrammar { name: "hare", exported_symbol: "tree_sitter_hare", abi: 15, scanner_language: "none", source_hash: "0b3a1e895885d404bd6d1d5477bef4ef22fd13a065839a4d8c9151e5f14501c9" },
    GeneratedGrammar { name: "haskell", exported_symbol: "tree_sitter_haskell", abi: 15, scanner_language: "c", source_hash: "cdd05db6d02761c33baf199aeab22de284f148575b49b6778d222425d78f7975" },
    GeneratedGrammar { name: "hcl", exported_symbol: "tree_sitter_hcl", abi: 15, scanner_language: "c", source_hash: "4fc6908038004460dcbfc7d6e879cf6b408ec142cfe43f6c0039ffe8d10d5fce" },
    GeneratedGrammar { name: "hlsl", exported_symbol: "tree_sitter_hlsl", abi: 14, scanner_language: "c", source_hash: "4ccb043bfb7caedcc6f07516dcfe8c661e35ff1e6ffb63152b44720e0134e631" },
    GeneratedGrammar { name: "html", exported_symbol: "tree_sitter_html", abi: 14, scanner_language: "c", source_hash: "cb4770e087003344742620e8c9d24f854bcd87a44c0a0cf2e03f73632805281d" },
    GeneratedGrammar { name: "hyprlang", exported_symbol: "tree_sitter_hyprlang", abi: 15, scanner_language: "none", source_hash: "8f12d0f9dda5017360341bb324b2ea6ea4bd6a7b2f5bd571ce505b2502167ff9" },
    GeneratedGrammar { name: "ini", exported_symbol: "tree_sitter_ini", abi: 15, scanner_language: "none", source_hash: "450ed4785bb243c3e789419d0102ea57e0416f65c22d7b3a5afd8ca4727892cc" },
    GeneratedGrammar { name: "ispc", exported_symbol: "tree_sitter_ispc", abi: 14, scanner_language: "none", source_hash: "d3053a66eb44f0bd7310d0d5fe84f69de52766ac5d8a7b2c171c1720ad9f4b60" },
    GeneratedGrammar { name: "janet", exported_symbol: "tree_sitter_janet_simple", abi: 14, scanner_language: "c", source_hash: "e88383ce245792282d827ea42176804dfc4235953904f72e562e1331c9483263" },
    GeneratedGrammar { name: "java", exported_symbol: "tree_sitter_java", abi: 14, scanner_language: "none", source_hash: "a3c161ef02722c53ba3561bc46fc6ba159ad4ad8f4d84b2d4beef1451595427e" },
    GeneratedGrammar { name: "javascript", exported_symbol: "tree_sitter_javascript", abi: 15, scanner_language: "c", source_hash: "a458936c9b7b9f849b136c9fce9878fca3654447aaf8001091e76a26b8c01bf3" },
    GeneratedGrammar { name: "jinja2", exported_symbol: "tree_sitter_jinja2", abi: 14, scanner_language: "none", source_hash: "df7fd60d7469c70c05792f11a2a9cd22c3e8d6e08154ee9b78fb9bf45d0038b0" },
    GeneratedGrammar { name: "jsdoc", exported_symbol: "tree_sitter_jsdoc", abi: 15, scanner_language: "c", source_hash: "6cd8e6e30a7fc850cf91bfe344829a7b912a87cf10dfd3020049cdcb7298ba12" },
    GeneratedGrammar { name: "json", exported_symbol: "tree_sitter_json", abi: 14, scanner_language: "none", source_hash: "832d348e402d6295341ee6fba0353b75987cd1a5f7699a1f0ba0709e1ef2efe9" },
    GeneratedGrammar { name: "json5", exported_symbol: "tree_sitter_json5", abi: 15, scanner_language: "none", source_hash: "153fa29e82f1467a68a299d100d761a634b14057eedb81c48260665af394f039" },
    GeneratedGrammar { name: "jsonnet", exported_symbol: "tree_sitter_jsonnet", abi: 14, scanner_language: "c", source_hash: "f15beca6f76131c5e915383e5479d0c7e2d5691eabfe771b56977f27d08a1761" },
    GeneratedGrammar { name: "julia", exported_symbol: "tree_sitter_julia", abi: 15, scanner_language: "c", source_hash: "68bfde946531f5721406d39f1cb0315aadecaf1b77b0d205b6d0ef397be3df24" },
    GeneratedGrammar { name: "just", exported_symbol: "tree_sitter_just", abi: 15, scanner_language: "c", source_hash: "32b3ddf3ec9a3464d59b38fe97003c91c340b3670005501d8367b431e9072f61" },
    GeneratedGrammar { name: "kconfig", exported_symbol: "tree_sitter_kconfig", abi: 14, scanner_language: "c", source_hash: "f7c2a0124bf7a235feb8ac54aefb9a88cca9df8cb40542e48def86a4c49409eb" },
    GeneratedGrammar { name: "kdl", exported_symbol: "tree_sitter_kdl", abi: 14, scanner_language: "c", source_hash: "83c499453458370afe24030960c4e07b822bf9591b4dbb1044361263d5c3ba33" },
    GeneratedGrammar { name: "kotlin", exported_symbol: "tree_sitter_kotlin", abi: 14, scanner_language: "c", source_hash: "26acc37f5492a792cd5fbede75ed869c9da76aa6248fef821fdf0d7d9b95cb17" },
    GeneratedGrammar { name: "lean", exported_symbol: "tree_sitter_lean", abi: 13, scanner_language: "c", source_hash: "ede922e18e1272af265e009c2b02022a163d2953c6fa88b835fd5ba08b6cceaf" },
    GeneratedGrammar { name: "linkerscript", exported_symbol: "tree_sitter_linkerscript", abi: 14, scanner_language: "none", source_hash: "c18c046ef4003b3e59070f24f1240a8db0348466d5c307fa33f651ea1768762e" },
    GeneratedGrammar { name: "liquid", exported_symbol: "tree_sitter_liquid", abi: 14, scanner_language: "c", source_hash: "c62d60e9bd3395870289741b0ddd279fc5e66ed6e1e1f17078167b61f978bd74" },
    GeneratedGrammar { name: "llvm", exported_symbol: "tree_sitter_llvm", abi: 15, scanner_language: "none", source_hash: "b031294ef0222e63eace95cf8af0b653b0ded3cb10ff32da7e832548793cee55" },
    GeneratedGrammar { name: "lua", exported_symbol: "tree_sitter_lua", abi: 15, scanner_language: "c", source_hash: "b67e7504c943cbb684ec49a32eee2368d7dff92d7ad70fb58f6aca83999407f3" },
    GeneratedGrammar { name: "luau", exported_symbol: "tree_sitter_luau", abi: 14, scanner_language: "c", source_hash: "17616d509d35c1e728014096bcc12d49e1cfc939a7cbdcbdc36913625a5fdfc9" },
    GeneratedGrammar { name: "magma", exported_symbol: "tree_sitter_magma", abi: 15, scanner_language: "none", source_hash: "176e3213b944ee770eb31dd8fa6509cd670cd214255095436ee973fcc01aa4c1" },
    GeneratedGrammar { name: "make", exported_symbol: "tree_sitter_make", abi: 15, scanner_language: "none", source_hash: "659db4c0f568a8a9447f2166a6147e664eb9f054863856ee5305dbd818509324" },
    GeneratedGrammar { name: "markdown", exported_symbol: "tree_sitter_markdown", abi: 15, scanner_language: "c", source_hash: "51c61f6c789c23e2f33c564af6cfe1ca3225396906aaaecb4649ea2559008407" },
    GeneratedGrammar { name: "matlab", exported_symbol: "tree_sitter_matlab", abi: 15, scanner_language: "c", source_hash: "423891f4e08cdb2a4711c4260f8cb2bf4690de75d39cb3a703a3a6a50f9840f3" },
    GeneratedGrammar { name: "mermaid", exported_symbol: "tree_sitter_mermaid", abi: 14, scanner_language: "none", source_hash: "a1b856278b8f85ec188309c2049f57e5d7abcc55d7dff3e1b945cace2a6dd15e" },
    GeneratedGrammar { name: "meson", exported_symbol: "tree_sitter_meson", abi: 15, scanner_language: "none", source_hash: "33bd01ffca2229b970d893a97af30b48431f0ab6e7eedba7614ce6587502bd5b" },
    GeneratedGrammar { name: "mojo", exported_symbol: "tree_sitter_mojo", abi: 15, scanner_language: "c", source_hash: "21435b43fe498ef7b84bf60fcff506a755203df904b266147d4ce2e693e6ee05" },
    GeneratedGrammar { name: "move", exported_symbol: "tree_sitter_move", abi: 14, scanner_language: "none", source_hash: "c0bdf3e25a5d30093fb74852c2a8be98221ce2cb25a7e37fb438567dfe396dc7" },
    GeneratedGrammar { name: "nasm", exported_symbol: "tree_sitter_nasm", abi: 14, scanner_language: "none", source_hash: "63029c17d1a73e69b00a88062d75a299da8e21215fa6ccf3c71da86249793949" },
    GeneratedGrammar { name: "nickel", exported_symbol: "tree_sitter_nickel", abi: 15, scanner_language: "c", source_hash: "6bed0818e71a38e151ba96bec0019068d5164ac7a6827b07ddc25e3afc2ffe30" },
    GeneratedGrammar { name: "nix", exported_symbol: "tree_sitter_nix", abi: 13, scanner_language: "c", source_hash: "5e16d68a7e94e4a5cf7724d846d5fe68b15f6ae95df5c1e0e0885581d7b2eb4f" },
    GeneratedGrammar { name: "objc", exported_symbol: "tree_sitter_objc", abi: 14, scanner_language: "none", source_hash: "7bea8fc0a430020c1878ef54eeca9a08283697e26aba9c3c8b5cb55c5ca28147" },
    GeneratedGrammar { name: "ocaml", exported_symbol: "tree_sitter_ocaml", abi: 14, scanner_language: "c", source_hash: "12f70d5bcd3788fa34515b2c6bf271fa2dc42dc054e4bd9cf5f2286fdc582256" },
    GeneratedGrammar { name: "odin", exported_symbol: "tree_sitter_odin", abi: 14, scanner_language: "c", source_hash: "2284dd432e1257db983ca8d6675571ecb342563ac2b5f21206dc0d3aa397a011" },
    GeneratedGrammar { name: "pascal", exported_symbol: "tree_sitter_pascal", abi: 14, scanner_language: "none", source_hash: "03cca5d5fbdc67da4d621f820f9c28168f0048d4ea57af45fd4872f130b35f6c" },
    GeneratedGrammar { name: "perl", exported_symbol: "tree_sitter_perl", abi: 14, scanner_language: "c", source_hash: "0084236de2358f4f9de28990b86d402e8a443bd18b83ca87c52f44f0a11a1a18" },
    GeneratedGrammar { name: "php", exported_symbol: "tree_sitter_php_only", abi: 15, scanner_language: "c", source_hash: "1dabf10844d8adc397ead3542dfe619b19b44efa246130945cfea12b5995701c" },
    GeneratedGrammar { name: "pine", exported_symbol: "tree_sitter_pine", abi: 14, scanner_language: "c", source_hash: "e85ff5534acfa315ce4d3a5b18f5d7426039c596b395f75b2d8c07f21bddfa97" },
    GeneratedGrammar { name: "pkl", exported_symbol: "tree_sitter_pkl", abi: 15, scanner_language: "c", source_hash: "ec5b096248788e2c4cd96f6a81cccde43f965e86ed332272ed2de89c0c92e76c" },
    GeneratedGrammar { name: "po", exported_symbol: "tree_sitter_po", abi: 14, scanner_language: "none", source_hash: "300ff04668b1172630739cd2e64e1ad56482593856aae983719f95c3caf58249" },
    GeneratedGrammar { name: "pony", exported_symbol: "tree_sitter_pony", abi: 14, scanner_language: "c", source_hash: "a6a0c9822ed3c526c4e616850cda37fc789ebe3bf93d2f54a29c8058f94acd9c" },
    GeneratedGrammar { name: "powershell", exported_symbol: "tree_sitter_powershell", abi: 15, scanner_language: "c", source_hash: "674883ce5e0397faec80f4c9d66ec41f403f7885665b13eae39aba28e5d6bc77" },
    GeneratedGrammar { name: "prisma", exported_symbol: "tree_sitter_prisma", abi: 15, scanner_language: "none", source_hash: "de751218ad3f19dee9c2aa6841869caf22d98a4af2aed76aa21c54649ef2b8e5" },
    GeneratedGrammar { name: "properties", exported_symbol: "tree_sitter_properties", abi: 14, scanner_language: "c", source_hash: "6474f66b0462f298f7c617b21168e2b1376e5bf4a4787472f95225ece31d7036" },
    GeneratedGrammar { name: "protobuf", exported_symbol: "tree_sitter_proto", abi: 13, scanner_language: "none", source_hash: "3674a504321ce1918c2cd27dcc4bc6821c0d12a7299424f63acba5d2580746c9" },
    GeneratedGrammar { name: "puppet", exported_symbol: "tree_sitter_puppet", abi: 14, scanner_language: "none", source_hash: "884f4baa0601f72799596fa48dea24dd015633f539df44aa5f903ffe6b7c83d6" },
    GeneratedGrammar { name: "purescript", exported_symbol: "tree_sitter_purescript", abi: 15, scanner_language: "c", source_hash: "0a0098a40e5129b44804807b8fc04200e8482e0c552224ff889397fdcecc2846" },
    GeneratedGrammar { name: "python", exported_symbol: "tree_sitter_python", abi: 15, scanner_language: "c", source_hash: "5598358f7540d247f67cfab737e86a11bacb0e52a1afcdadde085e7d3440217f" },
    GeneratedGrammar { name: "qml", exported_symbol: "tree_sitter_qmljs", abi: 14, scanner_language: "c", source_hash: "40c95dd7f258340802a6496fe6062595b51a099c36f9fa5f500d44cac1694609" },
    GeneratedGrammar { name: "r", exported_symbol: "tree_sitter_r", abi: 14, scanner_language: "c", source_hash: "c119cbd6cbd58dc2cb37979f261a2d1abb4ca03ed278e4c75b6e3c338ac80707" },
    GeneratedGrammar { name: "racket", exported_symbol: "tree_sitter_racket", abi: 14, scanner_language: "c", source_hash: "369ef5803f960c849eb3ba087ff7deeac4199f32b481ea06f69882520f583d8a" },
    GeneratedGrammar { name: "regex", exported_symbol: "tree_sitter_regex", abi: 15, scanner_language: "none", source_hash: "86ac315155b039569b6263cf8e79e69ea6f31e1884104c464bbc614d5e327782" },
    GeneratedGrammar { name: "requirements", exported_symbol: "tree_sitter_requirements", abi: 14, scanner_language: "none", source_hash: "fea24eed492c1cb9b43b04074f939ed042d0a8267bfad1ac98c09290bff96809" },
    GeneratedGrammar { name: "rescript", exported_symbol: "tree_sitter_rescript", abi: 15, scanner_language: "c", source_hash: "c9d9d49397daab24f05c6850c3d7c8d7095fee570916fe1f543266d33c027cac" },
    GeneratedGrammar { name: "ron", exported_symbol: "tree_sitter_ron", abi: 14, scanner_language: "c", source_hash: "e1f2385f72281c70f04a0ef2299a0af760d0a2bf2130688c70b2e31f4c61bec6" },
    GeneratedGrammar { name: "rst", exported_symbol: "tree_sitter_rst", abi: 14, scanner_language: "c", source_hash: "c676d0843e42f086ceda2d889c41cb83eccc67e97f11589a1175a72270bb9da7" },
    GeneratedGrammar { name: "ruby", exported_symbol: "tree_sitter_ruby", abi: 14, scanner_language: "c", source_hash: "69fadbdd026b2d24a8439808882177cefd6f1d6c8a909c733c9ed938c56120e4" },
    GeneratedGrammar { name: "rust", exported_symbol: "tree_sitter_rust", abi: 15, scanner_language: "c", source_hash: "9090688cd9c67d88f89bbcda27bc38cf3d4783b04659e66a054f4079b12b841b" },
    GeneratedGrammar { name: "scala", exported_symbol: "tree_sitter_scala", abi: 15, scanner_language: "c", source_hash: "9a14514faa534fcd293d97ced1a705152b4c65faead14e07f9081de6026f068e" },
    GeneratedGrammar { name: "scheme", exported_symbol: "tree_sitter_scheme", abi: 14, scanner_language: "none", source_hash: "ccd3976d5e70160d22196fba704900e3b0c29cf86f15439931f9e94103bb40e7" },
    GeneratedGrammar { name: "scss", exported_symbol: "tree_sitter_scss", abi: 13, scanner_language: "c", source_hash: "df7d9c6fbf5933c937cbe76cf85b2f11df396f905fdf20137e54620ea6963f33" },
    GeneratedGrammar { name: "slang", exported_symbol: "tree_sitter_slang", abi: 15, scanner_language: "c", source_hash: "89cf230b727f526e24b8e4b2b81698c8e71f83970d02f7ad6ec177fa73a5ee09" },
    GeneratedGrammar { name: "smali", exported_symbol: "tree_sitter_smali", abi: 14, scanner_language: "c", source_hash: "cc32df77f3329af0c41b870091bea0a8a60932d665bcf4b33103ac605f336067" },
    GeneratedGrammar { name: "smithy", exported_symbol: "tree_sitter_smithy", abi: 14, scanner_language: "none", source_hash: "16f6f86de019658db64615f2bbfba673ab7a6658f3065e0ed11b90bfa4e22df3" },
    GeneratedGrammar { name: "solidity", exported_symbol: "tree_sitter_solidity", abi: 15, scanner_language: "none", source_hash: "5792f8014681ab28845c94f6510aac72eaf566482f507f379ee2d110a13574ca" },
    GeneratedGrammar { name: "soql", exported_symbol: "tree_sitter_soql", abi: 14, scanner_language: "none", source_hash: "0bb9e37d518c30471a18dbad866b71318414b29afda611d31b2941652f8299ac" },
    GeneratedGrammar { name: "sosl", exported_symbol: "tree_sitter_sosl", abi: 14, scanner_language: "none", source_hash: "c5954a424947e9ef1bf576fee26b89b91ce565ebe22d877f27d962d853baa957" },
    GeneratedGrammar { name: "sql", exported_symbol: "tree_sitter_sql", abi: 15, scanner_language: "c", source_hash: "fa6226e81ca046e1e67b4f42c01f4bc208e1c734e38e69ad89b140a15b992385" },
    GeneratedGrammar { name: "squirrel", exported_symbol: "tree_sitter_squirrel", abi: 14, scanner_language: "c", source_hash: "8fb8802389c3222a3150f88dd31e5712e14231596d4244135a402aa8a5333089" },
    GeneratedGrammar { name: "sshconfig", exported_symbol: "tree_sitter_ssh_config", abi: 14, scanner_language: "none", source_hash: "b41e2fc17c06bfce7cb4d3df5a9a0d8a2a921cc83fe2ffb61f97f5da80767709" },
    GeneratedGrammar { name: "starlark", exported_symbol: "tree_sitter_starlark", abi: 14, scanner_language: "c", source_hash: "ddef78f645849ef78c1e7319d5ed6cfa2a1def8f01c171e9bf79a34316403b81" },
    GeneratedGrammar { name: "svelte", exported_symbol: "tree_sitter_svelte", abi: 14, scanner_language: "c", source_hash: "f1125c1d589fa2a667d417f995927695113da17499da3a537897cd9206294ef2" },
    GeneratedGrammar { name: "sway", exported_symbol: "tree_sitter_sway", abi: 14, scanner_language: "c", source_hash: "c09c4ea4e655e1731a4452b6ed10c4a231987b27822d8fea4747162b7fc13947" },
    GeneratedGrammar { name: "swift", exported_symbol: "tree_sitter_swift", abi: 14, scanner_language: "c", source_hash: "7f2f3b77ad75208c27cf9923b00446462ed9771613b5cc8e261171ea33d0a517" },
    GeneratedGrammar { name: "systemverilog", exported_symbol: "tree_sitter_systemverilog", abi: 15, scanner_language: "none", source_hash: "f977ff9857622e83f2e343fc451b1acbccc68ddd4f914f1605af1d08562c669e" },
    GeneratedGrammar { name: "tablegen", exported_symbol: "tree_sitter_tablegen", abi: 14, scanner_language: "c", source_hash: "1f5e938055a50af283c63f9d250567f2374a16dec471e52c910e2cee905f2bc1" },
    GeneratedGrammar { name: "tcl", exported_symbol: "tree_sitter_tcl", abi: 15, scanner_language: "c", source_hash: "83459605df626af1adb7bce9cb03c54fd716ae7b6623b1ddac397ed70efb0c72" },
    GeneratedGrammar { name: "teal", exported_symbol: "tree_sitter_teal", abi: 15, scanner_language: "c", source_hash: "77917f1a3b9981cb217c79f3c0d0f7f90e72f8b03c7fdcf9fb71e161162e94fc" },
    GeneratedGrammar { name: "templ", exported_symbol: "tree_sitter_templ", abi: 15, scanner_language: "c", source_hash: "280a9d60fb04b5fc14c3f37061fd3b1c983c8624965d7ffc333a23bb7a7d68ee" },
    GeneratedGrammar { name: "thrift", exported_symbol: "tree_sitter_thrift", abi: 14, scanner_language: "none", source_hash: "f4a72609a58c0cacaaa046ae0b2929b797beae50260c2f8e1374f2ccbd98df48" },
    GeneratedGrammar { name: "tlaplus", exported_symbol: "tree_sitter_tlaplus", abi: 14, scanner_language: "c", source_hash: "bfbc5146b6103d6b0c1f3a4d6c46b27c5f3c56edd88a4baa593362734d6984b6" },
    GeneratedGrammar { name: "toml", exported_symbol: "tree_sitter_toml", abi: 14, scanner_language: "c", source_hash: "4da93fc3b87dc1dcb000c99374629ed808deb193dc22a71a07deda46f764d82a" },
    GeneratedGrammar { name: "tsx", exported_symbol: "tree_sitter_tsx", abi: 14, scanner_language: "c", source_hash: "111680a35b846cc42200b0f48b71a0b9f5974deab727657040729f364bb4aca5" },
    GeneratedGrammar { name: "typescript", exported_symbol: "tree_sitter_typescript", abi: 14, scanner_language: "c", source_hash: "96478c525f717fabe9e2dba6926eb7dc0ba1c68f05db66dff710291d768bb7b3" },
    GeneratedGrammar { name: "typst", exported_symbol: "tree_sitter_typst", abi: 14, scanner_language: "c", source_hash: "4bda51f6523f7bc4c77deebb88339f3c9496f580eb35d86c75f6c7f38361e0d1" },
    GeneratedGrammar { name: "verilog", exported_symbol: "tree_sitter_verilog", abi: 13, scanner_language: "none", source_hash: "92eb00b0953168fce0b81d12ef8a0e4898850d85be37921e6134843a5277e805" },
    GeneratedGrammar { name: "vhdl", exported_symbol: "tree_sitter_vhdl", abi: 15, scanner_language: "c", source_hash: "81a612a48046589f6d9eda26478a2e9a28a35eeaaed8d207e4bf903feb3f4fc3" },
    GeneratedGrammar { name: "vim", exported_symbol: "tree_sitter_vim", abi: 15, scanner_language: "c", source_hash: "7ddea983c1ae29673fb1ded445facac5eedffe839a0945a1049d670410d141b3" },
    GeneratedGrammar { name: "vue", exported_symbol: "tree_sitter_vue", abi: 15, scanner_language: "c", source_hash: "aa705fae947fa54aa226006771aab919e82283006be029ac7272dbe67596daa6" },
    GeneratedGrammar { name: "wgsl", exported_symbol: "tree_sitter_wgsl", abi: 13, scanner_language: "c", source_hash: "a80b48ef2542855dc81f170513daf2e56b9f6fe0160f6cd241e6aadc54b936b5" },
    GeneratedGrammar { name: "wit", exported_symbol: "tree_sitter_wit", abi: 15, scanner_language: "c", source_hash: "e8052dfe7376fde4331d46eb2febae6fe2e6429b1018bff42b9e2a0f79906575" },
    GeneratedGrammar { name: "wolfram", exported_symbol: "tree_sitter_wolfram", abi: 13, scanner_language: "c", source_hash: "fb4214cb3b665d05db8f39e89166ccde7d506a90ca96f30d99ea021f52c8ab82" },
    GeneratedGrammar { name: "xml", exported_symbol: "tree_sitter_xml", abi: 14, scanner_language: "c", source_hash: "2d050250a22421fc561fb224bc84d371fdbb8978fc71aeedede76b69279ac010" },
    GeneratedGrammar { name: "yaml", exported_symbol: "tree_sitter_yaml", abi: 15, scanner_language: "c", source_hash: "cf48df798c4e0c179a91408c9190d7dd6ab8b3736df09626f7c42f977b421a95" },
    GeneratedGrammar { name: "zig", exported_symbol: "tree_sitter_zig", abi: 15, scanner_language: "none", source_hash: "c451463784b33252777af127332514acf5d2e87996e029643305bd517b877b4c" },
    GeneratedGrammar { name: "zsh", exported_symbol: "tree_sitter_zsh", abi: 14, scanner_language: "c", source_hash: "e933fd55ae05ff2be224f40327698fa352cd2f8ed6c94395248031f8469fa3a2" },
];

pub(crate) static LANGUAGES: [GeneratedLanguage; 160] = [
    GeneratedLanguage { id: "ada", availability: GeneratedAvailability::Available { grammar_index: 0 } },
    GeneratedLanguage { id: "agda", availability: GeneratedAvailability::Available { grammar_index: 1 } },
    GeneratedLanguage { id: "apex", availability: GeneratedAvailability::Available { grammar_index: 2 } },
    GeneratedLanguage { id: "assembly", availability: GeneratedAvailability::Available { grammar_index: 3 } },
    GeneratedLanguage { id: "astro", availability: GeneratedAvailability::Available { grammar_index: 4 } },
    GeneratedLanguage { id: "awk", availability: GeneratedAvailability::Available { grammar_index: 5 } },
    GeneratedLanguage { id: "bash", availability: GeneratedAvailability::Available { grammar_index: 6 } },
    GeneratedLanguage { id: "beancount", availability: GeneratedAvailability::Available { grammar_index: 7 } },
    GeneratedLanguage { id: "bibtex", availability: GeneratedAvailability::Available { grammar_index: 8 } },
    GeneratedLanguage { id: "bicep", availability: GeneratedAvailability::Available { grammar_index: 9 } },
    GeneratedLanguage { id: "bitbake", availability: GeneratedAvailability::Available { grammar_index: 10 } },
    GeneratedLanguage { id: "blade", availability: GeneratedAvailability::Available { grammar_index: 11 } },
    GeneratedLanguage { id: "c", availability: GeneratedAvailability::Available { grammar_index: 12 } },
    GeneratedLanguage { id: "cairo", availability: GeneratedAvailability::Available { grammar_index: 14 } },
    GeneratedLanguage { id: "capnp", availability: GeneratedAvailability::Available { grammar_index: 15 } },
    GeneratedLanguage { id: "cfml", availability: GeneratedAvailability::Available { grammar_index: 16 } },
    GeneratedLanguage { id: "cfscript", availability: GeneratedAvailability::Available { grammar_index: 17 } },
    GeneratedLanguage { id: "clojure", availability: GeneratedAvailability::Available { grammar_index: 18 } },
    GeneratedLanguage { id: "cmake", availability: GeneratedAvailability::Available { grammar_index: 19 } },
    GeneratedLanguage { id: "cobol", availability: GeneratedAvailability::Available { grammar_index: 20 } },
    GeneratedLanguage { id: "commonlisp", availability: GeneratedAvailability::Available { grammar_index: 21 } },
    GeneratedLanguage { id: "cpp", availability: GeneratedAvailability::Available { grammar_index: 22 } },
    GeneratedLanguage { id: "crystal", availability: GeneratedAvailability::Available { grammar_index: 23 } },
    GeneratedLanguage { id: "csharp", availability: GeneratedAvailability::Available { grammar_index: 13 } },
    GeneratedLanguage { id: "css", availability: GeneratedAvailability::Available { grammar_index: 24 } },
    GeneratedLanguage { id: "csv", availability: GeneratedAvailability::Available { grammar_index: 25 } },
    GeneratedLanguage { id: "cuda", availability: GeneratedAvailability::Available { grammar_index: 26 } },
    GeneratedLanguage { id: "dart", availability: GeneratedAvailability::Available { grammar_index: 28 } },
    GeneratedLanguage { id: "devicetree", availability: GeneratedAvailability::Available { grammar_index: 29 } },
    GeneratedLanguage { id: "diff", availability: GeneratedAvailability::Available { grammar_index: 30 } },
    GeneratedLanguage { id: "dlang", availability: GeneratedAvailability::Available { grammar_index: 27 } },
    GeneratedLanguage { id: "dockerfile", availability: GeneratedAvailability::Available { grammar_index: 31 } },
    GeneratedLanguage { id: "dotenv", availability: GeneratedAvailability::Available { grammar_index: 32 } },
    GeneratedLanguage { id: "elixir", availability: GeneratedAvailability::Available { grammar_index: 34 } },
    GeneratedLanguage { id: "elm", availability: GeneratedAvailability::Available { grammar_index: 35 } },
    GeneratedLanguage { id: "emacslisp", availability: GeneratedAvailability::Available { grammar_index: 33 } },
    GeneratedLanguage { id: "erlang", availability: GeneratedAvailability::Available { grammar_index: 36 } },
    GeneratedLanguage { id: "fennel", availability: GeneratedAvailability::Available { grammar_index: 37 } },
    GeneratedLanguage { id: "fish", availability: GeneratedAvailability::Available { grammar_index: 38 } },
    GeneratedLanguage { id: "form", availability: GeneratedAvailability::Available { grammar_index: 39 } },
    GeneratedLanguage { id: "fortran", availability: GeneratedAvailability::Available { grammar_index: 40 } },
    GeneratedLanguage { id: "fsharp", availability: GeneratedAvailability::Available { grammar_index: 41 } },
    GeneratedLanguage { id: "func", availability: GeneratedAvailability::Available { grammar_index: 42 } },
    GeneratedLanguage { id: "gdscript", availability: GeneratedAvailability::Available { grammar_index: 43 } },
    GeneratedLanguage { id: "gitattributes", availability: GeneratedAvailability::Available { grammar_index: 44 } },
    GeneratedLanguage { id: "gitignore", availability: GeneratedAvailability::Available { grammar_index: 45 } },
    GeneratedLanguage { id: "gleam", availability: GeneratedAvailability::Available { grammar_index: 46 } },
    GeneratedLanguage { id: "glsl", availability: GeneratedAvailability::Available { grammar_index: 47 } },
    GeneratedLanguage { id: "gn", availability: GeneratedAvailability::Available { grammar_index: 48 } },
    GeneratedLanguage { id: "go", availability: GeneratedAvailability::Available { grammar_index: 49 } },
    GeneratedLanguage { id: "gomod", availability: GeneratedAvailability::Available { grammar_index: 50 } },
    GeneratedLanguage { id: "gotemplate", availability: GeneratedAvailability::Available { grammar_index: 51 } },
    GeneratedLanguage { id: "graphql", availability: GeneratedAvailability::Available { grammar_index: 52 } },
    GeneratedLanguage { id: "groovy", availability: GeneratedAvailability::Available { grammar_index: 53 } },
    GeneratedLanguage { id: "hare", availability: GeneratedAvailability::Available { grammar_index: 54 } },
    GeneratedLanguage { id: "haskell", availability: GeneratedAvailability::Available { grammar_index: 55 } },
    GeneratedLanguage { id: "hcl", availability: GeneratedAvailability::Available { grammar_index: 56 } },
    GeneratedLanguage { id: "hlsl", availability: GeneratedAvailability::Available { grammar_index: 57 } },
    GeneratedLanguage { id: "html", availability: GeneratedAvailability::Available { grammar_index: 58 } },
    GeneratedLanguage { id: "hyprlang", availability: GeneratedAvailability::Available { grammar_index: 59 } },
    GeneratedLanguage { id: "ini", availability: GeneratedAvailability::Available { grammar_index: 60 } },
    GeneratedLanguage { id: "ispc", availability: GeneratedAvailability::Available { grammar_index: 61 } },
    GeneratedLanguage { id: "janet", availability: GeneratedAvailability::Available { grammar_index: 62 } },
    GeneratedLanguage { id: "java", availability: GeneratedAvailability::Available { grammar_index: 63 } },
    GeneratedLanguage { id: "javascript", availability: GeneratedAvailability::Available { grammar_index: 64 } },
    GeneratedLanguage { id: "jinja2", availability: GeneratedAvailability::Available { grammar_index: 65 } },
    GeneratedLanguage { id: "jsdoc", availability: GeneratedAvailability::Available { grammar_index: 66 } },
    GeneratedLanguage { id: "json", availability: GeneratedAvailability::Available { grammar_index: 67 } },
    GeneratedLanguage { id: "json5", availability: GeneratedAvailability::Available { grammar_index: 68 } },
    GeneratedLanguage { id: "jsonnet", availability: GeneratedAvailability::Available { grammar_index: 69 } },
    GeneratedLanguage { id: "julia", availability: GeneratedAvailability::Available { grammar_index: 70 } },
    GeneratedLanguage { id: "just", availability: GeneratedAvailability::Available { grammar_index: 71 } },
    GeneratedLanguage { id: "k8s", availability: GeneratedAvailability::Available { grammar_index: 154 } },
    GeneratedLanguage { id: "kconfig", availability: GeneratedAvailability::Available { grammar_index: 72 } },
    GeneratedLanguage { id: "kdl", availability: GeneratedAvailability::Available { grammar_index: 73 } },
    GeneratedLanguage { id: "kotlin", availability: GeneratedAvailability::Available { grammar_index: 74 } },
    GeneratedLanguage { id: "kustomize", availability: GeneratedAvailability::Available { grammar_index: 154 } },
    GeneratedLanguage { id: "lean", availability: GeneratedAvailability::Available { grammar_index: 75 } },
    GeneratedLanguage { id: "linkerscript", availability: GeneratedAvailability::Available { grammar_index: 76 } },
    GeneratedLanguage { id: "liquid", availability: GeneratedAvailability::Available { grammar_index: 77 } },
    GeneratedLanguage { id: "llvm_ir", availability: GeneratedAvailability::Available { grammar_index: 78 } },
    GeneratedLanguage { id: "lua", availability: GeneratedAvailability::Available { grammar_index: 79 } },
    GeneratedLanguage { id: "luau", availability: GeneratedAvailability::Available { grammar_index: 80 } },
    GeneratedLanguage { id: "magma", availability: GeneratedAvailability::Available { grammar_index: 81 } },
    GeneratedLanguage { id: "makefile", availability: GeneratedAvailability::Available { grammar_index: 82 } },
    GeneratedLanguage { id: "markdown", availability: GeneratedAvailability::Available { grammar_index: 83 } },
    GeneratedLanguage { id: "matlab", availability: GeneratedAvailability::Available { grammar_index: 84 } },
    GeneratedLanguage { id: "mermaid", availability: GeneratedAvailability::Available { grammar_index: 85 } },
    GeneratedLanguage { id: "meson", availability: GeneratedAvailability::Available { grammar_index: 86 } },
    GeneratedLanguage { id: "mojo", availability: GeneratedAvailability::Available { grammar_index: 87 } },
    GeneratedLanguage { id: "move", availability: GeneratedAvailability::Available { grammar_index: 88 } },
    GeneratedLanguage { id: "nasm", availability: GeneratedAvailability::Available { grammar_index: 89 } },
    GeneratedLanguage { id: "nickel", availability: GeneratedAvailability::Available { grammar_index: 90 } },
    GeneratedLanguage { id: "nim", availability: GeneratedAvailability::Unavailable { reason: "codebase-memory-mcp retains the language ID but has no lang_specs entry or Tree-sitter factory at the pinned commit" } },
    GeneratedLanguage { id: "nix", availability: GeneratedAvailability::Available { grammar_index: 91 } },
    GeneratedLanguage { id: "objc", availability: GeneratedAvailability::Available { grammar_index: 92 } },
    GeneratedLanguage { id: "ocaml", availability: GeneratedAvailability::Available { grammar_index: 93 } },
    GeneratedLanguage { id: "odin", availability: GeneratedAvailability::Available { grammar_index: 94 } },
    GeneratedLanguage { id: "pascal", availability: GeneratedAvailability::Available { grammar_index: 95 } },
    GeneratedLanguage { id: "perl", availability: GeneratedAvailability::Available { grammar_index: 96 } },
    GeneratedLanguage { id: "php", availability: GeneratedAvailability::Available { grammar_index: 97 } },
    GeneratedLanguage { id: "pine", availability: GeneratedAvailability::Available { grammar_index: 98 } },
    GeneratedLanguage { id: "pkl", availability: GeneratedAvailability::Available { grammar_index: 99 } },
    GeneratedLanguage { id: "po", availability: GeneratedAvailability::Available { grammar_index: 100 } },
    GeneratedLanguage { id: "pony", availability: GeneratedAvailability::Available { grammar_index: 101 } },
    GeneratedLanguage { id: "powershell", availability: GeneratedAvailability::Available { grammar_index: 102 } },
    GeneratedLanguage { id: "prisma", availability: GeneratedAvailability::Available { grammar_index: 103 } },
    GeneratedLanguage { id: "properties", availability: GeneratedAvailability::Available { grammar_index: 104 } },
    GeneratedLanguage { id: "protobuf", availability: GeneratedAvailability::Available { grammar_index: 105 } },
    GeneratedLanguage { id: "puppet", availability: GeneratedAvailability::Available { grammar_index: 106 } },
    GeneratedLanguage { id: "purescript", availability: GeneratedAvailability::Available { grammar_index: 107 } },
    GeneratedLanguage { id: "python", availability: GeneratedAvailability::Available { grammar_index: 108 } },
    GeneratedLanguage { id: "qml", availability: GeneratedAvailability::Available { grammar_index: 109 } },
    GeneratedLanguage { id: "r", availability: GeneratedAvailability::Available { grammar_index: 110 } },
    GeneratedLanguage { id: "racket", availability: GeneratedAvailability::Available { grammar_index: 111 } },
    GeneratedLanguage { id: "regex", availability: GeneratedAvailability::Available { grammar_index: 112 } },
    GeneratedLanguage { id: "requirements", availability: GeneratedAvailability::Available { grammar_index: 113 } },
    GeneratedLanguage { id: "rescript", availability: GeneratedAvailability::Available { grammar_index: 114 } },
    GeneratedLanguage { id: "ron", availability: GeneratedAvailability::Available { grammar_index: 115 } },
    GeneratedLanguage { id: "rst", availability: GeneratedAvailability::Available { grammar_index: 116 } },
    GeneratedLanguage { id: "ruby", availability: GeneratedAvailability::Available { grammar_index: 117 } },
    GeneratedLanguage { id: "rust", availability: GeneratedAvailability::Available { grammar_index: 118 } },
    GeneratedLanguage { id: "scala", availability: GeneratedAvailability::Available { grammar_index: 119 } },
    GeneratedLanguage { id: "scheme", availability: GeneratedAvailability::Available { grammar_index: 120 } },
    GeneratedLanguage { id: "scss", availability: GeneratedAvailability::Available { grammar_index: 121 } },
    GeneratedLanguage { id: "slang", availability: GeneratedAvailability::Available { grammar_index: 122 } },
    GeneratedLanguage { id: "smali", availability: GeneratedAvailability::Available { grammar_index: 123 } },
    GeneratedLanguage { id: "smithy", availability: GeneratedAvailability::Available { grammar_index: 124 } },
    GeneratedLanguage { id: "solidity", availability: GeneratedAvailability::Available { grammar_index: 125 } },
    GeneratedLanguage { id: "soql", availability: GeneratedAvailability::Available { grammar_index: 126 } },
    GeneratedLanguage { id: "sosl", availability: GeneratedAvailability::Available { grammar_index: 127 } },
    GeneratedLanguage { id: "sql", availability: GeneratedAvailability::Available { grammar_index: 128 } },
    GeneratedLanguage { id: "squirrel", availability: GeneratedAvailability::Available { grammar_index: 129 } },
    GeneratedLanguage { id: "sshconfig", availability: GeneratedAvailability::Available { grammar_index: 130 } },
    GeneratedLanguage { id: "starlark", availability: GeneratedAvailability::Available { grammar_index: 131 } },
    GeneratedLanguage { id: "svelte", availability: GeneratedAvailability::Available { grammar_index: 132 } },
    GeneratedLanguage { id: "sway", availability: GeneratedAvailability::Available { grammar_index: 133 } },
    GeneratedLanguage { id: "swift", availability: GeneratedAvailability::Available { grammar_index: 134 } },
    GeneratedLanguage { id: "systemverilog", availability: GeneratedAvailability::Available { grammar_index: 135 } },
    GeneratedLanguage { id: "tablegen", availability: GeneratedAvailability::Available { grammar_index: 136 } },
    GeneratedLanguage { id: "tcl", availability: GeneratedAvailability::Available { grammar_index: 137 } },
    GeneratedLanguage { id: "teal", availability: GeneratedAvailability::Available { grammar_index: 138 } },
    GeneratedLanguage { id: "templ", availability: GeneratedAvailability::Available { grammar_index: 139 } },
    GeneratedLanguage { id: "thrift", availability: GeneratedAvailability::Available { grammar_index: 140 } },
    GeneratedLanguage { id: "tlaplus", availability: GeneratedAvailability::Available { grammar_index: 141 } },
    GeneratedLanguage { id: "toml", availability: GeneratedAvailability::Available { grammar_index: 142 } },
    GeneratedLanguage { id: "tsx", availability: GeneratedAvailability::Available { grammar_index: 143 } },
    GeneratedLanguage { id: "typescript", availability: GeneratedAvailability::Available { grammar_index: 144 } },
    GeneratedLanguage { id: "typst", availability: GeneratedAvailability::Available { grammar_index: 145 } },
    GeneratedLanguage { id: "verilog", availability: GeneratedAvailability::Available { grammar_index: 146 } },
    GeneratedLanguage { id: "vhdl", availability: GeneratedAvailability::Available { grammar_index: 147 } },
    GeneratedLanguage { id: "vimscript", availability: GeneratedAvailability::Available { grammar_index: 148 } },
    GeneratedLanguage { id: "vue", availability: GeneratedAvailability::Available { grammar_index: 149 } },
    GeneratedLanguage { id: "wgsl", availability: GeneratedAvailability::Available { grammar_index: 150 } },
    GeneratedLanguage { id: "wit", availability: GeneratedAvailability::Available { grammar_index: 151 } },
    GeneratedLanguage { id: "wolfram", availability: GeneratedAvailability::Available { grammar_index: 152 } },
    GeneratedLanguage { id: "xml", availability: GeneratedAvailability::Available { grammar_index: 153 } },
    GeneratedLanguage { id: "yaml", availability: GeneratedAvailability::Available { grammar_index: 154 } },
    GeneratedLanguage { id: "zig", availability: GeneratedAvailability::Available { grammar_index: 155 } },
    GeneratedLanguage { id: "zsh", availability: GeneratedAvailability::Available { grammar_index: 156 } },
];

pub(crate) fn language_fn(grammar_index: usize) -> Option<LanguageFn> {
    FACTORIES.get(grammar_index).copied().map(|factory| {
        // SAFETY: every factory is a verified, linked Tree-sitter language entry.
        unsafe { LanguageFn::from_raw(factory) }
    })
}
