// @generated by tools/generate-index-language-specs.mjs; do not edit manually.
// Audited upstream: DeusData/codebase-memory-mcp@2469ecc3a7a2f80debe296e1f17a1efcfdb9450c

mod ada_cfml;
mod cfscript_diff;
mod dlang_glsl;
mod gn_javascript;
mod jinja2_makefile;
mod markdown_php;
mod pine_ron;
mod rst_svelte;
mod sway_typst;
mod verilog_zsh;

#[derive(Debug, Clone, Copy)]
pub(crate) struct LanguageSpec {
    pub id: &'static str,
    pub function_kinds: &'static [&'static str],
    pub class_kinds: &'static [&'static str],
    pub field_kinds: &'static [&'static str],
    pub module_kinds: &'static [&'static str],
    pub call_kinds: &'static [&'static str],
    pub import_kinds: &'static [&'static str],
    pub import_from_kinds: &'static [&'static str],
    pub branch_kinds: &'static [&'static str],
    pub variable_kinds: &'static [&'static str],
    pub assignment_kinds: &'static [&'static str],
    pub throw_kinds: &'static [&'static str],
    pub decorator_kinds: &'static [&'static str],
}

#[cfg(test)]
pub(crate) const AUDITED_LANGUAGE_SPEC_COUNT: usize = LANGUAGE_SPECS.len();

pub(crate) fn language_spec(language_id: &str) -> Option<&'static LanguageSpec> {
    LANGUAGE_SPECS
        .binary_search_by(|spec| spec.id.cmp(language_id))
        .ok()
        .and_then(|index| LANGUAGE_SPECS.get(index))
}

static LANGUAGE_SPECS: &[LanguageSpec] = &[
    ada_cfml::ADA,
    ada_cfml::AGDA,
    ada_cfml::APEX,
    ada_cfml::ASSEMBLY,
    ada_cfml::ASTRO,
    ada_cfml::AWK,
    ada_cfml::BASH,
    ada_cfml::BEANCOUNT,
    ada_cfml::BIBTEX,
    ada_cfml::BICEP,
    ada_cfml::BITBAKE,
    ada_cfml::BLADE,
    ada_cfml::C,
    ada_cfml::CAIRO,
    ada_cfml::CAPNP,
    ada_cfml::CFML,
    cfscript_diff::CFSCRIPT,
    cfscript_diff::CLOJURE,
    cfscript_diff::CMAKE,
    cfscript_diff::COBOL,
    cfscript_diff::COMMONLISP,
    cfscript_diff::CPP,
    cfscript_diff::CRYSTAL,
    cfscript_diff::CSHARP,
    cfscript_diff::CSS,
    cfscript_diff::CSV,
    cfscript_diff::CUDA,
    cfscript_diff::DART,
    cfscript_diff::DEVICETREE,
    cfscript_diff::DIFF,
    dlang_glsl::DLANG,
    dlang_glsl::DOCKERFILE,
    dlang_glsl::DOTENV,
    dlang_glsl::ELIXIR,
    dlang_glsl::ELM,
    dlang_glsl::EMACSLISP,
    dlang_glsl::ERLANG,
    dlang_glsl::FENNEL,
    dlang_glsl::FISH,
    dlang_glsl::FORM,
    dlang_glsl::FORTRAN,
    dlang_glsl::FSHARP,
    dlang_glsl::FUNC,
    dlang_glsl::GDSCRIPT,
    dlang_glsl::GITATTRIBUTES,
    dlang_glsl::GITIGNORE,
    dlang_glsl::GLEAM,
    dlang_glsl::GLSL,
    gn_javascript::GN,
    gn_javascript::GO,
    gn_javascript::GOMOD,
    gn_javascript::GOTEMPLATE,
    gn_javascript::GRAPHQL,
    gn_javascript::GROOVY,
    gn_javascript::HARE,
    gn_javascript::HASKELL,
    gn_javascript::HCL,
    gn_javascript::HLSL,
    gn_javascript::HTML,
    gn_javascript::HYPRLANG,
    gn_javascript::INI,
    gn_javascript::ISPC,
    gn_javascript::JANET,
    gn_javascript::JAVA,
    gn_javascript::JAVASCRIPT,
    jinja2_makefile::JINJA2,
    jinja2_makefile::JSDOC,
    jinja2_makefile::JSON,
    jinja2_makefile::JSON5,
    jinja2_makefile::JSONNET,
    jinja2_makefile::JULIA,
    jinja2_makefile::JUST,
    jinja2_makefile::K8S,
    jinja2_makefile::KCONFIG,
    jinja2_makefile::KDL,
    jinja2_makefile::KOTLIN,
    jinja2_makefile::KUSTOMIZE,
    jinja2_makefile::LEAN,
    jinja2_makefile::LINKERSCRIPT,
    jinja2_makefile::LIQUID,
    jinja2_makefile::LLVM_IR,
    jinja2_makefile::LUA,
    jinja2_makefile::LUAU,
    jinja2_makefile::MAGMA,
    jinja2_makefile::MAKEFILE,
    markdown_php::MARKDOWN,
    markdown_php::MATLAB,
    markdown_php::MERMAID,
    markdown_php::MESON,
    markdown_php::MOJO,
    markdown_php::MOVE,
    markdown_php::NASM,
    markdown_php::NICKEL,
    markdown_php::NIX,
    markdown_php::OBJC,
    markdown_php::OCAML,
    markdown_php::ODIN,
    markdown_php::PASCAL,
    markdown_php::PERL,
    markdown_php::PHP,
    pine_ron::PINE,
    pine_ron::PKL,
    pine_ron::PO,
    pine_ron::PONY,
    pine_ron::POWERSHELL,
    pine_ron::PRISMA,
    pine_ron::PROPERTIES,
    pine_ron::PROTOBUF,
    pine_ron::PUPPET,
    pine_ron::PURESCRIPT,
    pine_ron::PYTHON,
    pine_ron::QML,
    pine_ron::R,
    pine_ron::RACKET,
    pine_ron::REGEX,
    pine_ron::REQUIREMENTS,
    pine_ron::RESCRIPT,
    pine_ron::RON,
    rst_svelte::RST,
    rst_svelte::RUBY,
    rst_svelte::RUST,
    rst_svelte::SCALA,
    rst_svelte::SCHEME,
    rst_svelte::SCSS,
    rst_svelte::SLANG,
    rst_svelte::SMALI,
    rst_svelte::SMITHY,
    rst_svelte::SOLIDITY,
    rst_svelte::SOQL,
    rst_svelte::SOSL,
    rst_svelte::SQL,
    rst_svelte::SQUIRREL,
    rst_svelte::SSHCONFIG,
    rst_svelte::STARLARK,
    rst_svelte::SVELTE,
    sway_typst::SWAY,
    sway_typst::SWIFT,
    sway_typst::SYSTEMVERILOG,
    sway_typst::TABLEGEN,
    sway_typst::TCL,
    sway_typst::TEAL,
    sway_typst::TEMPL,
    sway_typst::THRIFT,
    sway_typst::TLAPLUS,
    sway_typst::TOML,
    sway_typst::TSX,
    sway_typst::TYPESCRIPT,
    sway_typst::TYPST,
    verilog_zsh::VERILOG,
    verilog_zsh::VHDL,
    verilog_zsh::VIMSCRIPT,
    verilog_zsh::VUE,
    verilog_zsh::WGSL,
    verilog_zsh::WIT,
    verilog_zsh::WOLFRAM,
    verilog_zsh::XML,
    verilog_zsh::YAML,
    verilog_zsh::ZIG,
    verilog_zsh::ZSH,
];

#[cfg(test)]
mod tests {
    use super::{AUDITED_LANGUAGE_SPEC_COUNT, LANGUAGE_SPECS, language_spec};

    #[test]
    fn registry_is_complete_sorted_and_matches_callable_pack() {
        assert_eq!(AUDITED_LANGUAGE_SPEC_COUNT, 159);
        assert!(
            LANGUAGE_SPECS
                .windows(2)
                .all(|pair| pair[0].id < pair[1].id)
        );
        assert!(language_spec("nim").is_none());
        assert!(language_spec("rust").is_some());
        assert!(language_spec("mojo").is_some());
    }
}
