// @generated by tools/generate-index-language-specs.mjs; do not edit manually.

use super::LanguageSpec;

pub(super) const VERILOG: LanguageSpec = LanguageSpec {
    id: "verilog",
    function_kinds: &[
        "function_declaration",
        "task_declaration",
        "function_body_declaration",
        "function_statement",
    ],
    class_kinds: &[
        "module_declaration",
        "class_declaration",
        "interface_declaration",
        "package_declaration",
        "type_declaration",
    ],
    field_kinds: &[],
    module_kinds: &["source_file"],
    call_kinds: &[
        "system_tf_call",
        "subroutine_call",
        "function_subroutine_call",
        "method_call",
    ],
    import_kinds: &["extends", "import", "package_import_declaration"],
    import_from_kinds: &[],
    branch_kinds: &["conditional_statement", "case_statement", "loop_statement"],
    variable_kinds: &["net_declaration", "data_declaration"],
    assignment_kinds: &["blocking_assignment", "nonblocking_assignment"],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const VHDL: LanguageSpec = LanguageSpec {
    id: "vhdl",
    function_kinds: &["subprogram_declaration", "subprogram_definition"],
    class_kinds: &[
        "entity_declaration",
        "architecture_definition",
        "component_declaration",
        "interface_declaration",
        "package_declaration",
        "protected_type_declaration",
        "record_type_definition",
        "type_declaration",
    ],
    field_kinds: &[],
    module_kinds: &["design_file"],
    call_kinds: &[
        "function_call",
        "procedure_call_statement",
        "component_instantiation_statement",
        "parenthesis_group",
    ],
    import_kinds: &["library_clause", "use_clause"],
    import_from_kinds: &[],
    branch_kinds: &["if_statement", "case_statement", "loop_statement"],
    variable_kinds: &[
        "variable_declaration",
        "signal_declaration",
        "constant_declaration",
    ],
    assignment_kinds: &["variable_assignment", "signal_assignment"],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const VIMSCRIPT: LanguageSpec = LanguageSpec {
    id: "vimscript",
    function_kinds: &[
        "function_definition",
        "function_declaration",
        "lambda_expression",
    ],
    class_kinds: &[],
    field_kinds: &[],
    module_kinds: &["script_file"],
    call_kinds: &["call_expression", "call", "command"],
    import_kinds: &["include"],
    import_from_kinds: &[],
    branch_kinds: &[
        "if_statement",
        "for_statement",
        "while_statement",
        "try_statement",
    ],
    variable_kinds: &["let_statement"],
    assignment_kinds: &["let_statement"],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const VUE: LanguageSpec = LanguageSpec {
    id: "vue",
    function_kinds: &[],
    class_kinds: &[],
    field_kinds: &[],
    module_kinds: &["document"],
    call_kinds: &[],
    import_kinds: &[],
    import_from_kinds: &[],
    branch_kinds: &[],
    variable_kinds: &[],
    assignment_kinds: &[],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const WGSL: LanguageSpec = LanguageSpec {
    id: "wgsl",
    function_kinds: &["function_declaration"],
    class_kinds: &[
        "struct_declaration",
        "type_alias_declaration",
        "type_declaration",
    ],
    field_kinds: &[],
    module_kinds: &["translation_unit"],
    call_kinds: &["type_constructor_or_function_call_expression"],
    import_kinds: &["enable_directive"],
    import_from_kinds: &[],
    branch_kinds: &[
        "if_statement",
        "switch_statement",
        "for_statement",
        "while_statement",
        "loop_statement",
    ],
    variable_kinds: &["variable_declaration"],
    assignment_kinds: &["assignment_statement"],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const WIT: LanguageSpec = LanguageSpec {
    id: "wit",
    function_kinds: &["func_item", "resource_method", "export_item", "import_item"],
    class_kinds: &[
        "record_item",
        "resource_item",
        "enum_items",
        "variant_items",
        "flags_items",
    ],
    field_kinds: &["record_field"],
    module_kinds: &["source_file"],
    call_kinds: &[],
    import_kinds: &[
        "import_item",
        "toplevel_use_item",
        "export_item",
        "import",
        "include",
        "include_item",
    ],
    import_from_kinds: &[],
    branch_kinds: &[],
    variable_kinds: &[],
    assignment_kinds: &[],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const WOLFRAM: LanguageSpec = LanguageSpec {
    id: "wolfram",
    function_kinds: &["set_delayed_top", "set_top", "set_delayed", "set"],
    class_kinds: &[],
    field_kinds: &[],
    module_kinds: &["source_file"],
    call_kinds: &["apply"],
    import_kinds: &["get_top"],
    import_from_kinds: &[],
    branch_kinds: &[],
    variable_kinds: &[],
    assignment_kinds: &[],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const XML: LanguageSpec = LanguageSpec {
    id: "xml",
    function_kinds: &[],
    class_kinds: &["element"],
    field_kinds: &[],
    module_kinds: &["document"],
    call_kinds: &[],
    import_kinds: &[],
    import_from_kinds: &[],
    branch_kinds: &[],
    variable_kinds: &[],
    assignment_kinds: &[],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const YAML: LanguageSpec = LanguageSpec {
    id: "yaml",
    function_kinds: &[],
    class_kinds: &[],
    field_kinds: &[],
    module_kinds: &["stream"],
    call_kinds: &[],
    import_kinds: &[],
    import_from_kinds: &[],
    branch_kinds: &[],
    variable_kinds: &["block_mapping_pair"],
    assignment_kinds: &[],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const ZIG: LanguageSpec = LanguageSpec {
    id: "zig",
    function_kinds: &[
        "function_declaration",
        "test_declaration",
        "function_signature",
    ],
    class_kinds: &[
        "struct_declaration",
        "enum_declaration",
        "union_declaration",
    ],
    field_kinds: &["container_field"],
    module_kinds: &["source_file"],
    call_kinds: &["call_expression", "builtin_function"],
    import_kinds: &["builtin_function"],
    import_from_kinds: &[],
    branch_kinds: &[
        "if_statement",
        "for_statement",
        "while_statement",
        "switch_expression",
    ],
    variable_kinds: &["variable_declaration"],
    assignment_kinds: &["assignment_expression"],
    throw_kinds: &[],
    decorator_kinds: &[],
};

pub(super) const ZSH: LanguageSpec = LanguageSpec {
    id: "zsh",
    function_kinds: &["function_definition"],
    class_kinds: &[],
    field_kinds: &[],
    module_kinds: &["program"],
    call_kinds: &["command", "call_expression"],
    import_kinds: &[],
    import_from_kinds: &[],
    branch_kinds: &[
        "if_statement",
        "case_statement",
        "while_statement",
        "for_statement",
    ],
    variable_kinds: &["variable_name"],
    assignment_kinds: &["variable_assignment"],
    throw_kinds: &[],
    decorator_kinds: &[],
};
