pub(super) const HTTP_LIBRARIES: &[&str] = &[
    "requests",
    "httpx",
    "aiohttp",
    "urllib",
    "urllib3",
    "httplib2",
    "pycurl",
    "treq",
    "uplink",
    "axios",
    "superagent",
    "needle",
    "node-fetch",
    "undici",
    "ofetch",
    "wretch",
    "sindresorhus/ky",
    "phin",
    "net/http",
    "resty",
    "sling",
    "heimdall",
    "gentleman",
    "retryablehttp",
    "HttpClient",
    "OkHttp",
    "okhttp3",
    "RestTemplate",
    "WebClient",
    "Unirest",
    "AsyncHttpClient",
    "apache.http",
    "Retrofit",
    "Feign",
    "ktor.client",
    "kittinunf.fuel",
    "reqwest",
    "hyper",
    "surf",
    "ureq",
    "isahc",
    "attohttpc",
    "RestSharp",
    "Flurl",
    "Refit",
    "HTTParty",
    "Faraday",
    "RestClient",
    "Typhoeus",
    "Excon",
    "Net::HTTP",
    "Guzzle",
    "guzzle",
    "curl",
    "Symfony\\HttpClient",
    "cpr",
    "cpp-httplib",
    "Poco.Net",
    "Beast",
    "Alamofire",
    "Moya",
    "URLSession",
    "Dio",
    "dio",
    "package:http",
    "Chopper",
    "HTTPoison",
    "Tesla",
    "Finch",
    "Mint.HTTP",
    "sttp",
    "akka.http",
    "http4s",
    "scalaj",
    "wreq",
    "http-client",
    "http-conduit",
    "servant-client",
    "Network.HTTP",
    "socket.http",
    "resty.http",
];

pub(super) const GRPC_LIBRARIES: &[&str] = &[
    "google.golang.org/grpc",
    "grpc.",
    "grpcio",
    "io.grpc",
    "ManagedChannel",
    "Grpc.Net.Client",
    "GrpcChannel",
    "Grpc.Core",
    "@grpc/grpc-js",
    "grpc-web",
    "tonic",
    "package:grpc",
];

pub(super) const GRAPHQL_LIBRARIES: &[&str] = &[
    "graphql",
    "apollo",
    "urql",
    "relay",
    "gqlgen",
    "juniper",
    "async-graphql",
    "graphene",
    "strawberry",
];

pub(super) const TRPC_LIBRARIES: &[&str] = &[
    "@trpc/server",
    "@trpc/client",
    "@trpc/react-query",
    "createTRPCRouter",
    "trpc.",
];

pub(super) const ASYNC_LIBRARIES: &[(&str, &str)] = &[
    ("cloudtasks", "cloud_tasks"),
    ("cloud_tasks", "cloud_tasks"),
    ("cloud.tasks", "cloud_tasks"),
    ("CloudTasks", "cloud_tasks"),
    ("pubsub", "pubsub"),
    ("cloud.pubsub", "pubsub"),
    ("PubSub", "pubsub"),
    ("aws-sdk-go/service/sqs", "sqs"),
    ("aws-sdk-go.service.sqs", "sqs"),
    ("aws_sdk_sqs", "sqs"),
    ("Amazon.SQS", "sqs"),
    ("@aws-sdk/client-sqs", "sqs"),
    ("boto3.client.sqs", "sqs"),
    ("aws-sdk-go/service/sns", "sns"),
    ("aws_sdk_sns", "sns"),
    ("Amazon.SNS", "sns"),
    ("@aws-sdk/client-sns", "sns"),
    ("eventbridge", "eventbridge"),
    ("EventBridge", "eventbridge"),
    ("aws_sdk_lambda", "lambda"),
    ("@aws-sdk/client-lambda", "lambda"),
    ("stepfunctions", "stepfunctions"),
    ("ServiceBus", "servicebus"),
    ("Azure.Messaging", "servicebus"),
    ("kafka", "kafka"),
    ("Kafka", "kafka"),
    ("kafkajs", "kafka"),
    ("sarama", "kafka"),
    ("rdkafka", "kafka"),
    ("confluent", "kafka"),
    ("amqp", "rabbitmq"),
    ("AMQP", "rabbitmq"),
    ("amqplib", "rabbitmq"),
    ("RabbitMQ", "rabbitmq"),
    ("lapin", "rabbitmq"),
    ("MassTransit", "rabbitmq"),
    ("nats", "nats"),
    ("NATS", "nats"),
    ("ioredis", "redis"),
    ("celery", "celery"),
    ("Celery", "celery"),
    ("dramatiq", "dramatiq"),
    ("huey", "huey"),
    ("python-rq", "rq"),
    ("rq.Queue", "rq"),
    ("bullmq", "bullmq"),
    ("BullMQ", "bullmq"),
    ("bull.Queue", "bull"),
    ("Sidekiq", "sidekiq"),
    ("sidekiq", "sidekiq"),
    ("Resque", "resque"),
    ("GoodJob", "goodjob"),
    ("DelayedJob", "delayed_job"),
    ("Hangfire", "hangfire"),
    ("NServiceBus", "nservicebus"),
    ("asynq", "asynq"),
    ("RichardKnop/machinery", "machinery"),
    ("temporalio", "temporal"),
    ("@temporalio", "temporal"),
    ("temporal.client", "temporal"),
    ("temporal.worker", "temporal"),
    ("inngest", "inngest"),
    ("Oban", "oban"),
    ("Broadway", "broadway"),
    ("GenStage", "genstage"),
    ("Phoenix.PubSub", "phoenix_pubsub"),
    ("Alpakka", "alpakka"),
    ("mqtt", "mqtt"),
    ("MQTTClient", "mqtt"),
    ("mosquitto", "mqtt"),
    ("rumqttc", "mqtt"),
    ("dapr.clients.grpc", "dapr"),
    ("DaprClient", "dapr"),
];
